Gourmet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("gourmets/", include("Michelin.urls")),
    path("send_email/", include("SendEmail.urls"))
]

Michelin/urls.py
from django.urls import path
from . import views

app_name = "michelin"
urlpatterns = [
    path("", views.index, name = "index"),
    path("new_category/", views.new_category, name = "new_category"),
    path("new_category/create", views.create_category, name = "create_category"),
    path("<int:category_id>/delete", views.delete_category, name = "delete_category"),
    path("<int:category_id>/restaurants", views.show_restaurants, name = "show_restaurants"),
    path("<int:category_id>/restaurants/new_restaurant", views.new_restaurant, name = "new_restaurant"),
    path("<int:category_id>/restaurants/new_restaurant/create", views.create_restaurant, name = "create_restaurant"),
    path("<int:category_id>/restaurants/<int:restaurant_id>", views.show_detail, name = "show_detail"),
    path("<int:category_id>/restaurants/<int:restaurant_id>/delete", views.delete_restaurant, name = "delete_restaurant")
]

SendEmail/urls.py
from django.urls import path
from . import views

app_name = "send_email"
urlpatterns = [
    path("", views.index, name = "email_index")
]

Michelin/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length = 100)
    date = models.DateTimeField(default = timezone.now())
    def __str__(self):
        return self.name

class Restaurant(models.Model):
    name = models.CharField(max_length = 100)
    link = models.CharField(max_length = 500)
    date = models.DateTimeField(default = timezone.now())
    description = models.TextField()
    keyword = models.CharField(max_length = 50)
    category = models.ForeignKey(Category, on_delete = models.CASCADE)
    def __str__(self):
        return self.name

SendEmail/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Email(models.Model):
    address = models.CharField(max_length = 50)
    title = models.CharField(max_length = 255)
    content = models.TextField()
    date = models.DateTimeField(default = timezone.now())
    def __str__(self):
        return self.title

Michelin/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Category, Restaurant

# Create your views here.
def index(request):
    categories = Category.objects.all()
    restaurants = Restaurant.objects.all()
    return render(request, "./index.html", {
        "categories": categories,
        "restaurants": restaurants
    })

def new_category(request):
    return render(request, "./new_category.html", {})

def create_category(request):
    name = request.POST["name"]
    category = Category(name = name)
    category.save()
    return HttpResponseRedirect(reverse("michelin:index"))

def show_restaurants(request, category_id):
    selected_category = Category.objects.get(id = category_id)
    restaurants = selected_category.restaurant_set.all()
    return render(request, "./restaurants.html", {
        "category": selected_category,
        "restaurants": restaurants
    })

def new_restaurant(request, category_id):
    selected_category = Category.objects.get(id = category_id)
    return render(request, "./new_restaurant.html", {
        "category": selected_category
    })

def create_restaurant(request, category_id):
    selected_category = Category.objects.get(id = category_id)
    name = request.POST["name"]
    link = request.POST["link"]
    description = request.POST["description"]
    keyword = request.POST["keyword"]
    new_restaurant = Restaurant(name = name, link = link, description = description, keyword = keyword, category = selected_category)
    new_restaurant.save()
    return HttpResponseRedirect(reverse("michelin:show_restaurants", args = (category_id,)))

def show_detail(request, category_id, restaurant_id):
    selected_category = Category.objects.get(id = category_id)
    selected_restaurant = selected_category.restaurant_set.get(id = restaurant_id)
    return render(request, "./restaurant_detail.html", {
        "category": selected_category,
        "restaurant": selected_restaurant
    })

def delete_category(request, category_id):
    Category.objects.filter(id = category_id).delete()
    return HttpResponseRedirect(reverse("michelin:index"))

def delete_restaurant(request, category_id, restaurant_id):
    Restaurant.objects.filter(id = restaurant_id).delete()
    return HttpResponseRedirect(reverse("michelin:show_restaurants", args = (category_id,)))

SendEmail/views.py
from django.shortcuts import render
from .models import Email

# Create your views here.
def index(request):
    address = request.POST["address"]
    title = request.POST["title"]
    content = request.POST["content"]
    new_email = Email(address = address, title = title, content = content)
    new_email.save()
    return render(request, "./email_index.html", {
        "address": address,
        "title": title,
        "content": content
    })

Michelin/templates/index.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Michelin Gourmet Selections</title>
</head>
<body>
    <h1>맛집 공유 사이트 built with Django</h1>
    <h2>카테고리</h2>
    <a href="{% url 'michelin:new_category' %}">카테고리 추가하기</a>
    {% if categories %}
    <ul>
        {% for category in categories %}
        <li>{{ category.name }}
            <a href="{% url 'michelin:show_restaurants' category.id %}">상세 보기</a>
            <a href="{% url 'michelin:delete_category' category.id %}">삭제</a>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>카테고리 없음</p>
    {% endif %}
    <h3>이메일 보내기</h3>
    <form action="/send_email/" method="POST">
        {% csrf_token %}
        <label for="address">수신자 주소</label>
        <input type="text" name="address" id="address" placeholder="수신자 이메일 주소를 입력하세요...">
        <label for="title">제목:</label>
        <input type="text" name="title" id="title" placeholder="제목을 입력하세요...">
        <label for="content">내용:</label>
        <textarea name="content" id="content" cols="30" rows="10" placeholder="내용을 입력하세요..."></textarea>
        <button type="submit">이메일 송신하기</button>
    </form>
</body>
</html>

Michelin/templates/new_category.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>새로운 카테고리 생성</title>
</head>
<body>
    <h1>새 카테고리 생성하기</h1>
    <form action="{% url 'michelin:create_category' %}" method="POST">
        {% csrf_token %}
        <label for="name">카테고리 이름:</label>
        <input type="text" name="name" id="name" placeholder="카테고리 이름을 입력하세요...">
        <button type="submit">생성!</button>
    </form>
    <a href="{% url 'michelin:index' %}">카테고리 화면으로 돌아가기</a>
</body>
</html>

Michelin/templates/new_restaurant.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>새 맛집 생성</title>
</head>
<body>
    <h1>{{ category.name }}에 대한 새 맛집 등록하기</h1>
    <form action="{% url 'michelin:create_restaurant' category.id %}" method="POST">
        {% csrf_token %}
        <label for="name">맛집 이름:</label>
        <input type="text" name="name" id="name" placeholder="맛집 이름을 입력하세요...">
        <label for="link">맛집 링크:</label>
        <input type="text" name="link" id="link" placeholder="맛집 링크를 입력하세요...">
        <label for="description">맛집 설명:</label>
        <textarea name="description" id="description" cols="30" rows="10" placeholder="맛집에 대한 설명을 추가하세요..."></textarea>
        <label for="keyword">맛집 키워드:</label>
        <input type="text" name="keyword" id="keyword" placeholder="맛집 키워드를 입력하세요...">
        <button type="submit">등록!</button>
    </form>
    <a href="{% url 'michelin:show_restaurants' category.id %}">맛집 화면으로 돌아가기</a>
</body>
</html>

Michelin/templates/restaurant_detail.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ restaurant.name }}</title>
</head>
<body>
    <h1>{{ category.name }} 카테고리의 {{ restaurant.name }}에 대한 상세 정보</h1>
    <h2>키워드: {{ restaurant.keyword }}</h2>
    <a href="{{ restaurant.link }}">맛집 웹사이트 방문하기</a>
    <p>{{ restaurant.description }}</p>
    <a href="{% url 'michelin:show_restaurants' category.id %}">맛집 화면으로 돌아가기</a>
</body>
</html>

Michelin/templates/restaurants.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ category.name }}</title>
</head>
<body>
    <h1>{{ category.name }}에 대한 맛집 목록</h1>
    <a href="{% url 'michelin:new_restaurant' category.id %}">맛집 추가하러 가기</a>
    {% if restaurants %}
    <ol>
        {% for restaurant in restaurants %}
        <li>{{ restaurant.name }}
            <a href="{% url 'michelin:show_detail' category.id restaurant.id %}">상세 보기</a>
            <a href="{% url 'michelin:delete_restaurant' category.id restaurant.id %}">삭제</a>
        </li>
        {% endfor %}
    </ol>
    {% else %}
    <p>아직 맛집이 없어요!</p>
    {% endif %}
    <a href="{% url 'michelin:index' %}">카테고리 사이트로 돌아가기</a>
</body>
</html>

SendEmail/templates/email_index.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>이메일 전송 완료</title>
</head>
<body>
    <h1>이메일을 성공적으로 전송하였습니다!</h1>
    <h2>수신자: {{ address }}</h2>
    <h3>제목: {{ title }}</h3>
    <p>내용: {{ content }}</p>
    <a href="{% url 'michelin:index' %}">메인 화면으로 돌아가기</a>
</body>
</html>

SendEmail/templates/index.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>이메일 전송 완료</title>
</head>
<body>
    <h1>이메일을 성공적으로 전송하였습니다!</h1>
    <h2>수신자: {{ address }}</h2>
    <h3>제목: {{ title }}</h3>
    <p>내용: {{ content }}</p>
    <a href="{% url 'send_email:index' %}">메인 화면으로 돌아가기</a>
</body>
</html>